### ISSUE TITLE
Is this still maintained?

### ISSUE THREAD

**Issue by MonssafToukal** [LCSB-BioCore/DistributedData.jl#43]
I was wondering if this package was still maintained. I would like to test it and possible work with it, but I also want to make sure that what I'm working on can be used in the future. The work you guys have done is amazing and it would greatly simplify my use of parallel workers.

**Comment by exaexa** [comment]
Hi, yeah, we use this package, and if we find problems we will fix them. There's not been much new functionality lately but that's mainly because we didn't have new usecases, feel free to ask if you'd have anything particular in mind.

**Comment by MonssafToukal** [comment]
Thanks a lot for your quick answer!
